// Copyright 2025 Vee.Qor. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace VGameplayTags
{

// Input Tags //
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PrimaryAttack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AirAttack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_StanceShift)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AbilityOne)

// Player Tags //
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump_Cooldown)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_PrimaryAttack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_AirSlash)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_StanceShift)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_BloodPact)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_BloodPact_Cooldown)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Combat)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Travel)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_InAir)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_OnGround)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Attacking)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_StanceShifting)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_BloodPactActivation)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwordTrace)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_StanceShift)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_BuffApplied)

// GameplayCue Tags //
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_BloodPact_BloodyBlades)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_CameraShake)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_Impact)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_React)

}