// Copyright 2025 Vee.Qor. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace VGameplayTags
{

// Input Tags //
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PrimaryAttack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AirAttack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_StanceShift)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AbilityOne)

// Player Tags //
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_AirSlash)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_BloodPact)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_BloodPact_Cooldown)

// Common Tags //
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Ability_PrimaryAttack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Ability_StanceShift)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Ability_Jump)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Ability_Jump_Cooldown)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Ability_Hit_React)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Ability_Death)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_Combat)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_Travel)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_OnGround)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_InAir)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_Attacking)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_StanceShifting)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_Casting)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_Dead)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_AttackTrace)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_CanAttack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_ResetAttack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_StanceShift)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_BuffApplied)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_Hit_React)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_Death)

// GameplayCue Tags //
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_BloodPact_BloodyBlades)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_CameraShake)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_Impact)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_Impact_QoP)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Hit_Impact_BuffBlack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Death_Dissolve)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Death_Dissolve_QoP)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Death_Dissolve_BuffBlack)

}